# Completion
autoload -U compinit
compinit

# Correction
setopt correctall

# Prompt
autoload -U promptinit
promptinit
prompt oliver

# Other options
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt autocd
setopt extendedglob

# Aliases
alias oldvim="vim"
alias vim="nvim"
alias vi="nvim"

# Env variables
export HISTSIZE=2000
export HISTFILE=~/.zsh_history
export SAVEHIST=$HISTSIZE

export GOPATH="$HOME/.proj"
export PATH="$PATH:$HOME/.proj/bin"
export PATH="$PATH:$HOME/.cargo/bin"

# GPG
GPG_TTY=$(tty)
export GPG_TTY

eval "$(fasd --init auto)"
