# Set Oh My ZSH variables
ZSH=/usr/share/oh-my-zsh
ZSH_THEME="amuse"
DISABLE_AUTO_UPDATE="true"

# Oh My ZSH plugins
plugins=(archlinux cargo colored-man-pages command-not-found common-aliases docker docker-compose encode64 fasd gitfast golang gpg-agent helm jsontools kubectl minikube npm rust ssh-agent sudo systemd ufw urltools)

# Set path
export GOPATH="$HOME/.proj"
export PATH="$PATH:$HOME/.proj/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export EDITOR="nvim"

# Aliases
alias oldvim="vim"
alias vim="nvim"
alias vi="nvim"

# Create Oh My ZSH cache dir
ZSH_CACHE_DIR=$HOME/.cache/oh-my-zsh
if [[ ! -d $ZSH_CACHE_DIR ]]; then
  mkdir $ZSH_CACHE_DIR
fi

# Set colors
(cat ~/.cache/wal/sequences &)

# Init Zoxide
eval "$(zoxide init zsh)"

source $ZSH/oh-my-zsh.sh
source ~/.config/sway/env
